import type {
  ActivityLog,
  ArrestRecord,
  Case,
  Crime,
  Criminal,
  Evidence,
  Notification,
  PoliceOfficer,
} from "./types";

export const mockCriminals: Criminal[] = [
  {
    id: 1,
    name: "Marcus Webb",
    gender: "Male",
    age: 34,
    photoUrl: "",
    address: "14 Oak St, Detroit, MI",
    crimeType: "Robbery",
    status: "Arrested",
    riskLevel: "High",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    name: "Elena Voss",
    gender: "Female",
    age: 28,
    photoUrl: "",
    address: "88 Pine Ave, Chicago, IL",
    crimeType: "Fraud",
    status: "Active",
    riskLevel: "Medium",
    createdAt: "2024-02-03",
  },
  {
    id: 3,
    name: "Tony Russo",
    gender: "Male",
    age: 45,
    photoUrl: "",
    address: "7 South Blvd, New York, NY",
    crimeType: "Murder",
    status: "Arrested",
    riskLevel: "Critical",
    createdAt: "2023-11-20",
  },
  {
    id: 4,
    name: "Dana Kim",
    gender: "Female",
    age: 31,
    photoUrl: "",
    address: "23 Elm Rd, Los Angeles, CA",
    crimeType: "Drug Trafficking",
    status: "Active",
    riskLevel: "High",
    createdAt: "2024-03-10",
  },
  {
    id: 5,
    name: "Jorge Mendez",
    gender: "Male",
    age: 38,
    photoUrl: "",
    address: "56 Maple Dr, Houston, TX",
    crimeType: "Assault",
    status: "Released",
    riskLevel: "Medium",
    createdAt: "2024-01-28",
  },
  {
    id: 6,
    name: "Priya Sharma",
    gender: "Female",
    age: 26,
    photoUrl: "",
    address: "102 Cedar Ln, Phoenix, AZ",
    crimeType: "Cybercrime",
    status: "Active",
    riskLevel: "Medium",
    createdAt: "2024-04-05",
  },
  {
    id: 7,
    name: "Samuel Brooks",
    gender: "Male",
    age: 52,
    photoUrl: "",
    address: "9 River St, Philadelphia, PA",
    crimeType: "Corruption",
    status: "Arrested",
    riskLevel: "High",
    createdAt: "2023-12-01",
  },
  {
    id: 8,
    name: "Ingrid Larson",
    gender: "Female",
    age: 29,
    photoUrl: "",
    address: "77 Oak Ave, San Antonio, TX",
    crimeType: "Theft",
    status: "Released",
    riskLevel: "Low",
    createdAt: "2024-02-14",
  },
  {
    id: 9,
    name: "Kevin Osei",
    gender: "Male",
    age: 41,
    photoUrl: "",
    address: "31 West St, Dallas, TX",
    crimeType: "Kidnapping",
    status: "Arrested",
    riskLevel: "Critical",
    createdAt: "2024-01-05",
  },
  {
    id: 10,
    name: "Maria Santos",
    gender: "Female",
    age: 36,
    photoUrl: "",
    address: "64 North Rd, San Jose, CA",
    crimeType: "Money Laundering",
    status: "Active",
    riskLevel: "High",
    createdAt: "2024-03-22",
  },
  {
    id: 11,
    name: "Derek Flynn",
    gender: "Male",
    age: 33,
    photoUrl: "",
    address: "18 Park Blvd, Austin, TX",
    crimeType: "Vandalism",
    status: "Released",
    riskLevel: "Low",
    createdAt: "2024-04-11",
  },
  {
    id: 12,
    name: "Aisha Mohammed",
    gender: "Female",
    age: 44,
    photoUrl: "",
    address: "90 Forest Ave, Jacksonville, FL",
    crimeType: "Fraud",
    status: "Active",
    riskLevel: "Medium",
    createdAt: "2024-02-27",
  },
  {
    id: 13,
    name: "Vladimir Petrov",
    gender: "Male",
    age: 50,
    photoUrl: "",
    address: "5 Harbor Dr, San Diego, CA",
    crimeType: "Arms Trafficking",
    status: "Arrested",
    riskLevel: "Critical",
    createdAt: "2023-10-14",
  },
  {
    id: 14,
    name: "Lily Chen",
    gender: "Female",
    age: 23,
    photoUrl: "",
    address: "41 Sunrise Blvd, Columbus, OH",
    crimeType: "Identity Theft",
    status: "Active",
    riskLevel: "Medium",
    createdAt: "2024-04-18",
  },
  {
    id: 15,
    name: "Ray Denton",
    gender: "Male",
    age: 47,
    photoUrl: "",
    address: "66 Valley Rd, Charlotte, NC",
    crimeType: "Drug Trafficking",
    status: "Deceased",
    riskLevel: "High",
    createdAt: "2023-08-30",
  },
];

export const mockCrimes: Crime[] = [
  {
    id: 1,
    title: "Downtown Bank Robbery",
    description:
      "Armed robbery at First National Bank. Three suspects entered at 10:30 AM.",
    crimeDate: "2024-01-14",
    location: "Detroit, MI",
    severity: "Severe",
    reportedById: "officer1",
  },
  {
    id: 2,
    title: "Corporate Fraud Scheme",
    description:
      "Multi-million dollar investment fraud targeting elderly victims.",
    crimeDate: "2024-02-01",
    location: "Chicago, IL",
    severity: "Moderate",
    reportedById: "officer2",
  },
  {
    id: 3,
    title: "Homicide on 5th Ave",
    description: "Victim found deceased. Signs of struggle at the scene.",
    crimeDate: "2023-11-19",
    location: "New York, NY",
    severity: "Critical",
    reportedById: "officer1",
  },
  {
    id: 4,
    title: "Drug Distribution Network",
    description: "Large scale narcotics distribution operation dismantled.",
    crimeDate: "2024-03-08",
    location: "Los Angeles, CA",
    severity: "Severe",
    reportedById: "officer3",
  },
  {
    id: 5,
    title: "Bar Fight Assault",
    description: "Aggravated assault resulting in serious injury.",
    crimeDate: "2024-01-27",
    location: "Houston, TX",
    severity: "Moderate",
    reportedById: "officer2",
  },
  {
    id: 6,
    title: "Ransomware Attack",
    description: "City infrastructure hit by ransomware, systems compromised.",
    crimeDate: "2024-04-03",
    location: "Phoenix, AZ",
    severity: "Severe",
    reportedById: "investigator1",
  },
  {
    id: 7,
    title: "Bribery at City Hall",
    description: "Public official caught accepting bribes for permits.",
    crimeDate: "2023-11-30",
    location: "Philadelphia, PA",
    severity: "Severe",
    reportedById: "officer1",
  },
  {
    id: 8,
    title: "Residential Burglary",
    description: "String of break-ins in Oak Hills neighborhood.",
    crimeDate: "2024-02-13",
    location: "San Antonio, TX",
    severity: "Minor",
    reportedById: "officer3",
  },
  {
    id: 9,
    title: "Child Abduction",
    description: "Minor abducted from school premises. Amber Alert issued.",
    crimeDate: "2024-01-04",
    location: "Dallas, TX",
    severity: "Critical",
    reportedById: "officer2",
  },
  {
    id: 10,
    title: "Shell Company Laundering",
    description:
      "Network of shell companies used to launder criminal proceeds.",
    crimeDate: "2024-03-20",
    location: "San Jose, CA",
    severity: "Severe",
    reportedById: "investigator1",
  },
];

export const mockOfficers: PoliceOfficer[] = [
  {
    id: 1,
    name: "Chief Robert Harmon",
    rank: "Commissioner",
    badgeNumber: "B-001",
    station: "Central HQ",
  },
  {
    id: 2,
    name: "Insp. Sarah Collins",
    rank: "Inspector",
    badgeNumber: "B-012",
    station: "North Precinct",
  },
  {
    id: 3,
    name: "Insp. David Park",
    rank: "Inspector",
    badgeNumber: "B-015",
    station: "South Precinct",
  },
  {
    id: 4,
    name: "Sgt. Mike Torres",
    rank: "Sergeant",
    badgeNumber: "B-031",
    station: "East Division",
  },
  {
    id: 5,
    name: "Sgt. Angela White",
    rank: "Sergeant",
    badgeNumber: "B-034",
    station: "West Division",
  },
  {
    id: 6,
    name: "Sgt. James Brown",
    rank: "Sergeant",
    badgeNumber: "B-037",
    station: "Central HQ",
  },
  {
    id: 7,
    name: "Const. Nina Lopez",
    rank: "Constable",
    badgeNumber: "B-088",
    station: "North Precinct",
  },
  {
    id: 8,
    name: "Const. Eric Stone",
    rank: "Constable",
    badgeNumber: "B-091",
    station: "South Precinct",
  },
];

export const mockArrestRecords: ArrestRecord[] = [
  {
    id: 1,
    criminalId: 1,
    officerId: 4,
    arrestDate: "2024-01-15",
    location: "Detroit, MI",
    notes: "Apprehended fleeing the scene. No injuries to officers.",
  },
  {
    id: 2,
    criminalId: 3,
    officerId: 2,
    arrestDate: "2023-11-20",
    location: "New York, NY",
    notes: "Arrested at residence. Weapon recovered.",
  },
  {
    id: 3,
    criminalId: 7,
    officerId: 6,
    arrestDate: "2023-12-01",
    location: "Philadelphia, PA",
    notes: "Cooperative during arrest. Evidence secured.",
  },
  {
    id: 4,
    criminalId: 9,
    officerId: 4,
    arrestDate: "2024-01-05",
    location: "Dallas, TX",
    notes: "Joint operation with FBI. Victim recovered safely.",
  },
  {
    id: 5,
    criminalId: 13,
    officerId: 3,
    arrestDate: "2023-10-14",
    location: "San Diego, CA",
    notes: "Large arms cache seized at warehouse.",
  },
  {
    id: 6,
    criminalId: 1,
    officerId: 7,
    arrestDate: "2022-06-10",
    location: "Detroit, MI",
    notes: "Prior arrest for petty theft. Released on bail.",
  },
  {
    id: 7,
    criminalId: 5,
    officerId: 8,
    arrestDate: "2024-01-28",
    location: "Houston, TX",
    notes: "Arrested at bar scene. Bail granted.",
  },
  {
    id: 8,
    criminalId: 2,
    officerId: 2,
    arrestDate: "2023-07-22",
    location: "Chicago, IL",
    notes: "Arrested on warrant. Released pending trial.",
  },
  {
    id: 9,
    criminalId: 4,
    officerId: 5,
    arrestDate: "2023-09-15",
    location: "Los Angeles, CA",
    notes: "DEA joint operation. Released on technicality.",
  },
  {
    id: 10,
    criminalId: 10,
    officerId: 3,
    arrestDate: "2024-03-22",
    location: "San Jose, CA",
    notes: "Financial crime arrest. Assets frozen.",
  },
  {
    id: 11,
    criminalId: 6,
    officerId: 2,
    arrestDate: "2024-04-05",
    location: "Phoenix, AZ",
    notes: "Cyber unit operation. Device seized.",
  },
  {
    id: 12,
    criminalId: 14,
    officerId: 7,
    arrestDate: "2024-04-18",
    location: "Columbus, OH",
    notes: "Fraud unit warrant.",
  },
  {
    id: 13,
    criminalId: 8,
    officerId: 8,
    arrestDate: "2024-02-14",
    location: "San Antonio, TX",
    notes: "Caught during burglary. Minor offense.",
  },
  {
    id: 14,
    criminalId: 12,
    officerId: 4,
    arrestDate: "2024-02-27",
    location: "Jacksonville, FL",
    notes: "Financial investigation ongoing.",
  },
  {
    id: 15,
    criminalId: 11,
    officerId: 6,
    arrestDate: "2024-04-11",
    location: "Austin, TX",
    notes: "Vandalism at public property.",
  },
];

export const mockCases: Case[] = [
  {
    id: 1,
    crimeId: 1,
    criminalId: 1,
    assignedOfficerId: 2,
    caseStatus: "Under Investigation",
    courtDate: "2024-08-15",
    description: "Bank robbery case. Forensic evidence being processed.",
  },
  {
    id: 2,
    crimeId: 3,
    criminalId: 3,
    assignedOfficerId: 2,
    caseStatus: "Under Investigation",
    courtDate: "2024-09-20",
    description: "Homicide. DNA evidence submitted to lab.",
  },
  {
    id: 3,
    crimeId: 7,
    criminalId: 7,
    assignedOfficerId: 3,
    caseStatus: "Closed",
    courtDate: "2024-05-10",
    description: "Bribery case. Defendant convicted.",
  },
  {
    id: 4,
    crimeId: 9,
    criminalId: 9,
    assignedOfficerId: 4,
    caseStatus: "Closed",
    courtDate: "2024-06-01",
    description: "Kidnapping. Defendant sentenced to 15 years.",
  },
  {
    id: 5,
    crimeId: 5,
    criminalId: 5,
    assignedOfficerId: 6,
    caseStatus: "Dismissed",
    courtDate: "2024-04-18",
    description:
      "Assault charges. Dismissed due to lack of witness cooperation.",
  },
  {
    id: 6,
    crimeId: 6,
    criminalId: 6,
    assignedOfficerId: 2,
    caseStatus: "Open",
    courtDate: "2024-10-05",
    description: "Cybercrime investigation. Digital forensics ongoing.",
  },
  {
    id: 7,
    crimeId: 4,
    criminalId: 4,
    assignedOfficerId: 5,
    caseStatus: "Under Investigation",
    courtDate: "2024-11-12",
    description: "Drug trafficking. Multiple defendants being processed.",
  },
  {
    id: 8,
    crimeId: 2,
    criminalId: 2,
    assignedOfficerId: 3,
    caseStatus: "Open",
    courtDate: "2024-12-01",
    description: "Fraud case. Financial records subpoenaed.",
  },
  {
    id: 9,
    crimeId: 10,
    criminalId: 10,
    assignedOfficerId: 3,
    caseStatus: "Under Investigation",
    courtDate: "2025-01-15",
    description: "Money laundering. International cooperation requested.",
  },
  {
    id: 10,
    crimeId: 8,
    criminalId: 8,
    assignedOfficerId: 7,
    caseStatus: "Closed",
    courtDate: "2024-04-30",
    description: "Burglary case. Guilty plea entered.",
  },
  {
    id: 11,
    crimeId: 9,
    criminalId: 9,
    assignedOfficerId: 4,
    caseStatus: "Closed",
    courtDate: "2024-03-01",
    description: "Related charges. Concurrent sentencing.",
  },
  {
    id: 12,
    crimeId: 1,
    criminalId: 1,
    assignedOfficerId: 6,
    caseStatus: "Open",
    courtDate: "2024-09-30",
    description: "Additional charges for prior robbery.",
  },
];

export const mockEvidence: Evidence[] = [
  {
    id: 1,
    caseId: 1,
    evidenceType: "Physical",
    description: "Ski mask found at scene",
    storageLocation: "Evidence Room A-12",
    collectedDate: "2024-01-15",
    collectedById: "officer1",
  },
  {
    id: 2,
    caseId: 1,
    evidenceType: "Digital",
    description: "ATM camera footage",
    storageLocation: "Digital Vault DV-04",
    collectedDate: "2024-01-15",
    collectedById: "investigator1",
  },
  {
    id: 3,
    caseId: 2,
    evidenceType: "Forensic",
    description: "DNA sample from crime scene",
    storageLocation: "Forensic Lab FL-03",
    collectedDate: "2023-11-20",
    collectedById: "officer2",
  },
  {
    id: 4,
    caseId: 2,
    evidenceType: "Physical",
    description: "Victim's belongings",
    storageLocation: "Evidence Room B-05",
    collectedDate: "2023-11-20",
    collectedById: "officer2",
  },
  {
    id: 5,
    caseId: 3,
    evidenceType: "Documentary",
    description: "Financial transaction records",
    storageLocation: "Records Office R-09",
    collectedDate: "2023-12-01",
    collectedById: "investigator1",
  },
  {
    id: 6,
    caseId: 4,
    evidenceType: "Testimonial",
    description: "Witness statements x3",
    storageLocation: "Case Files CF-04",
    collectedDate: "2024-01-06",
    collectedById: "officer1",
  },
  {
    id: 7,
    caseId: 5,
    evidenceType: "Digital",
    description: "Surveillance footage from bar",
    storageLocation: "Digital Vault DV-07",
    collectedDate: "2024-01-28",
    collectedById: "officer3",
  },
  {
    id: 8,
    caseId: 6,
    evidenceType: "Digital",
    description: "Malware source code samples",
    storageLocation: "Cyber Lab CL-01",
    collectedDate: "2024-04-04",
    collectedById: "investigator1",
  },
  {
    id: 9,
    caseId: 6,
    evidenceType: "Physical",
    description: "Server hardware seized",
    storageLocation: "Evidence Room C-02",
    collectedDate: "2024-04-05",
    collectedById: "officer2",
  },
  {
    id: 10,
    caseId: 7,
    evidenceType: "Physical",
    description: "2.3kg narcotics sample",
    storageLocation: "Secure Storage SS-07",
    collectedDate: "2024-03-09",
    collectedById: "officer3",
  },
  {
    id: 11,
    caseId: 7,
    evidenceType: "Documentary",
    description: "Distribution ledger",
    storageLocation: "Records Office R-12",
    collectedDate: "2024-03-09",
    collectedById: "investigator1",
  },
  {
    id: 12,
    caseId: 8,
    evidenceType: "Documentary",
    description: "False investment prospectus",
    storageLocation: "Records Office R-14",
    collectedDate: "2024-02-03",
    collectedById: "investigator1",
  },
  {
    id: 13,
    caseId: 9,
    evidenceType: "Forensic",
    description: "Digital forensics on seized laptops",
    storageLocation: "Forensic Lab FL-08",
    collectedDate: "2024-03-23",
    collectedById: "investigator1",
  },
  {
    id: 14,
    caseId: 9,
    evidenceType: "Documentary",
    description: "Bank account statements 2020-2024",
    storageLocation: "Records Office R-18",
    collectedDate: "2024-03-25",
    collectedById: "officer3",
  },
  {
    id: 15,
    caseId: 10,
    evidenceType: "Physical",
    description: "Stolen jewelry recovered",
    storageLocation: "Evidence Room A-22",
    collectedDate: "2024-02-14",
    collectedById: "officer3",
  },
  {
    id: 16,
    caseId: 11,
    evidenceType: "Testimonial",
    description: "Victim statement",
    storageLocation: "Case Files CF-11",
    collectedDate: "2024-01-05",
    collectedById: "officer1",
  },
  {
    id: 17,
    caseId: 12,
    evidenceType: "Digital",
    description: "CCTV footage from bank",
    storageLocation: "Digital Vault DV-12",
    collectedDate: "2024-01-16",
    collectedById: "officer2",
  },
  {
    id: 18,
    caseId: 1,
    evidenceType: "Forensic",
    description: "Fingerprints on counter",
    storageLocation: "Forensic Lab FL-01",
    collectedDate: "2024-01-16",
    collectedById: "officer1",
  },
  {
    id: 19,
    caseId: 2,
    evidenceType: "Physical",
    description: "Murder weapon - recovered knife",
    storageLocation: "Evidence Room B-09",
    collectedDate: "2023-11-22",
    collectedById: "officer2",
  },
  {
    id: 20,
    caseId: 3,
    evidenceType: "Testimonial",
    description: "Whistleblower testimony",
    storageLocation: "Case Files CF-03",
    collectedDate: "2023-12-03",
    collectedById: "investigator1",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 1,
    userId: "admin",
    action: "Created criminal record",
    entityType: "Criminal",
    entityId: "15",
    timestamp: "2024-04-18T09:12:00Z",
  },
  {
    id: 2,
    userId: "officer1",
    action: "Updated case status",
    entityType: "Case",
    entityId: "6",
    timestamp: "2024-04-18T09:45:00Z",
  },
  {
    id: 3,
    userId: "investigator1",
    action: "Added evidence",
    entityType: "Evidence",
    entityId: "20",
    timestamp: "2024-04-17T14:30:00Z",
  },
  {
    id: 4,
    userId: "officer2",
    action: "Filed arrest record",
    entityType: "ArrestRecord",
    entityId: "12",
    timestamp: "2024-04-17T11:20:00Z",
  },
  {
    id: 5,
    userId: "admin",
    action: "Added police officer",
    entityType: "Officer",
    entityId: "8",
    timestamp: "2024-04-16T16:00:00Z",
  },
  {
    id: 6,
    userId: "officer3",
    action: "Reported new crime",
    entityType: "Crime",
    entityId: "10",
    timestamp: "2024-04-16T10:55:00Z",
  },
  {
    id: 7,
    userId: "investigator1",
    action: "Updated evidence description",
    entityType: "Evidence",
    entityId: "13",
    timestamp: "2024-04-15T13:40:00Z",
  },
  {
    id: 8,
    userId: "officer1",
    action: "Assigned officer to case",
    entityType: "Case",
    entityId: "9",
    timestamp: "2024-04-15T09:00:00Z",
  },
  {
    id: 9,
    userId: "admin",
    action: "Deleted criminal record",
    entityType: "Criminal",
    entityId: "7",
    timestamp: "2024-04-14T17:22:00Z",
  },
  {
    id: 10,
    userId: "officer2",
    action: "Created case",
    entityType: "Case",
    entityId: "12",
    timestamp: "2024-04-14T12:11:00Z",
  },
  {
    id: 11,
    userId: "investigator1",
    action: "Updated case description",
    entityType: "Case",
    entityId: "8",
    timestamp: "2024-04-13T15:30:00Z",
  },
  {
    id: 12,
    userId: "officer3",
    action: "Updated criminal status",
    entityType: "Criminal",
    entityId: "4",
    timestamp: "2024-04-13T10:00:00Z",
  },
  {
    id: 13,
    userId: "admin",
    action: "User login",
    entityType: "User",
    entityId: "admin",
    timestamp: "2024-04-18T08:55:00Z",
  },
  {
    id: 14,
    userId: "officer1",
    action: "User login",
    entityType: "User",
    entityId: "officer1",
    timestamp: "2024-04-18T09:01:00Z",
  },
  {
    id: 15,
    userId: "investigator1",
    action: "User login",
    entityType: "User",
    entityId: "investigator1",
    timestamp: "2024-04-17T14:25:00Z",
  },
  {
    id: 16,
    userId: "officer2",
    action: "Added evidence",
    entityType: "Evidence",
    entityId: "19",
    timestamp: "2024-04-12T11:40:00Z",
  },
  {
    id: 17,
    userId: "admin",
    action: "Updated officer rank",
    entityType: "Officer",
    entityId: "3",
    timestamp: "2024-04-11T09:30:00Z",
  },
  {
    id: 18,
    userId: "officer3",
    action: "Created arrest record",
    entityType: "ArrestRecord",
    entityId: "15",
    timestamp: "2024-04-11T14:15:00Z",
  },
  {
    id: 19,
    userId: "investigator1",
    action: "Reported crime",
    entityType: "Crime",
    entityId: "6",
    timestamp: "2024-04-05T11:00:00Z",
  },
  {
    id: 20,
    userId: "officer1",
    action: "Created criminal record",
    entityType: "Criminal",
    entityId: "1",
    timestamp: "2024-01-15T10:00:00Z",
  },
  {
    id: 21,
    userId: "officer2",
    action: "Created case",
    entityType: "Case",
    entityId: "1",
    timestamp: "2024-01-16T09:00:00Z",
  },
  {
    id: 22,
    userId: "admin",
    action: "System backup",
    entityType: "System",
    entityId: "N/A",
    timestamp: "2024-04-18T02:00:00Z",
  },
  {
    id: 23,
    userId: "officer3",
    action: "Updated case status",
    entityType: "Case",
    entityId: "7",
    timestamp: "2024-03-12T16:00:00Z",
  },
  {
    id: 24,
    userId: "investigator1",
    action: "Flagged evidence",
    entityType: "Evidence",
    entityId: "8",
    timestamp: "2024-04-08T10:30:00Z",
  },
  {
    id: 25,
    userId: "admin",
    action: "Password reset for user",
    entityType: "User",
    entityId: "officer3",
    timestamp: "2024-04-10T11:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 1,
    title: "New Case Assigned",
    message: "Case #12 has been assigned to you for investigation.",
    notifType: "case",
    isRead: false,
    createdAt: "2024-04-18T09:50:00Z",
  },
  {
    id: 2,
    title: "Evidence Added",
    message: "New evidence uploaded to Case #9: Bank statements 2020-2024.",
    notifType: "evidence",
    isRead: false,
    createdAt: "2024-04-17T14:35:00Z",
  },
  {
    id: 3,
    title: "Critical Criminal Alert",
    message: "Criminal #13 flagged as high-risk - updated status.",
    notifType: "alert",
    isRead: false,
    createdAt: "2024-04-16T08:20:00Z",
  },
  {
    id: 4,
    title: "Court Date Reminder",
    message:
      "Case #3 court date is on May 10, 2024. Ensure evidence is prepared.",
    notifType: "reminder",
    isRead: true,
    createdAt: "2024-04-15T06:00:00Z",
  },
  {
    id: 5,
    title: "New Crime Reported",
    message: "Crime reported: Shell Company Laundering in San Jose, CA.",
    notifType: "crime",
    isRead: false,
    createdAt: "2024-03-20T15:00:00Z",
  },
  {
    id: 6,
    title: "Case Status Updated",
    message: "Case #5 has been dismissed. See case notes for details.",
    notifType: "case",
    isRead: true,
    createdAt: "2024-04-18T10:00:00Z",
  },
  {
    id: 7,
    title: "Arrest Record Filed",
    message: "New arrest record filed for Elena Voss (Criminal #2).",
    notifType: "arrest",
    isRead: true,
    createdAt: "2024-04-17T11:25:00Z",
  },
  {
    id: 8,
    title: "System Maintenance",
    message:
      "Scheduled maintenance on April 20th at 2:00 AM. Expect brief downtime.",
    notifType: "system",
    isRead: false,
    createdAt: "2024-04-18T07:00:00Z",
  },
];
